"""empty message

Revision ID: 5018f2033467
Revises: 2a710081315c
Create Date: 2022-08-05 22:49:13.718413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5018f2033467'
down_revision = '2a710081315c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE todo SET completed = False WHERE completed IS NULL;')
    # ### end Alembic commands ###

    op.alter_column('todo', 'completed', nullable = False)
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
